TITLE="Beej's Guide to C Programming"
SUBTITLE="Library Reference"
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v0.9.9, Copyright © December 30, 2022"

GUIDE_ID=bgclr

BGBSPD_BUILD_DIR?=../../bgbspd

#WEB_IMAGES=$(wildcard img_*svg)

include $(BGBSPD_BUILD_DIR)/source.make

